// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"auth-service/pkg/api"
	"auth-service/pkg/api/service"
	"auth-service/pkg/config"
	"auth-service/pkg/db"
	"auth-service/pkg/repository"
	"auth-service/pkg/service/token"
	"auth-service/pkg/usecase"
)

// Injectors from wire.go:

func InitializeAPI(cfg config.Config) (*api.Server, error) {
	gormDB, err := db.ConnectDatabase(cfg)
	if err != nil {
		return nil, err
	}
	authRepo := repository.NewAuthRepo(gormDB)
	tokenAuth := token.NewJwtTokenAuth(cfg)
	authUseCase := usecase.NewAuthUseCase(authRepo, tokenAuth)
	authServiceServer := service.NewAuthServiceServer(authUseCase)
	server, err := api.NewServerGRPC(cfg, authServiceServer)
	if err != nil {
		return nil, err
	}
	return server, nil
}
