// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"api-gateway/pkg/api"
	"api-gateway/pkg/api/handler"
	"api-gateway/pkg/api/middleware"
	"api-gateway/pkg/api/routes"
	"api-gateway/pkg/client"
	"api-gateway/pkg/config"
)

// Injectors from wire.go:

func InitializeAPI(cfg config.Config) (*api.Server, error) {
	authServiceClient, err := client.NewAuthServiceClient(cfg)
	if err != nil {
		return nil, err
	}
	interfacesMiddleware := middleware.NewMiddleware(authServiceClient)
	authHandler := handler.NewAuthHandler(authServiceClient)
	companyServiceClient, err := client.NewCompanyServiceClient(cfg)
	if err != nil {
		return nil, err
	}
	companyHandler := handler.NewCompanyHandler(companyServiceClient)
	httpHandler := routes.NewGinRouter(interfacesMiddleware, authHandler, companyHandler)
	server := api.NewServerHTTP(cfg, httpHandler)
	return server, nil
}
